name: Run Automated Tests

on:
  workflow_dispatch:
  push:
    branches:
      -main
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout todolist APP
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Checkout test repo
        run: git clone https://github.com/drestrepor/taller4-testing-playwright.git

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install tests deps
        run: |
          cd taller4-testing-playwright
          npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd taller4-testing-playwright
          npx playwright test todolist.spec.ts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: plawright report
          path: taller4-testing-playwright/playwright-report/
          retention-days: 30
